---
- name: config firewall
  hosts: gateway
  become: yes
  
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./yandex-cloud-terraform/hosts
        dest: /etc
        owner: root
        group: root
        mode: '0644'
        
- name: config nfs
  hosts: nfs
  become: yes
  
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./yandex-cloud-terraform/hosts
        dest: /etc
        owner: root
        group: root
        mode: '0644'    
    
