name: terraform_2
on:
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../yandex-cloud-terraform    
    steps:
    
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          install -m 600 -D /dev/null ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PUBLUC_KEY }}" > ~/.ssh/id_rsa.pub
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: ls
        run: ls -Al  
        
      - name: go to terraform config directory
        run: cd ./yandex-cloud-terraform
        
      - name: ls
        run: ls -Al  
             
      - name: check format Terraform
        run: terraform fmt
        
      - name: init Terraform
        run: terraform init
        
      - name: validate Terraform
        run: terraform validate
        
      - name: plan Terraform
        run: terraform plan
        
      - name: apply Terraform
        run: terraform apply
        
#    - uses: hashicorp/terraform-github-actions/fmt@latest
#    - uses: hashicorp/terraform-github-actions/init@latest
#    - uses: hashicorp/terraform-github-actions/validate@latest
#    - uses: hashicorp/terraform-github-actions/plan@latest
#    - uses: hashicorp/terraform-github-actions/apply@latest
