name: terraform_2
on:
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: hashicorp/terraform-github-actions/fmt@latest
    - uses: hashicorp/terraform-github-actions/init@latest
    - uses: hashicorp/terraform-github-actions/validate@latest
    - uses: hashicorp/terraform-github-actions/plan@latest
    - uses: hashicorp/terraform-github-actions/apply@latest
