name: terraform_2
on:
  workflow_dispatch:
env:
      DAY_OF_WEEK: Mon
      OAUTH: "${{ secrets.YC_OAUTH}}"
      cloud: "${{ secrets.YC_CLOUD}}"
      folder: "${{secrets.YC_FOLDER}}"
#defaults:
#  run:
#    working-directory: ../yandex-cloud-terraform
jobs:
  terraform:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ../yandex-cloud-terraform    
    steps:
    
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          install -m 600 -D /dev/null ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PUBLUC_KEY }}" > ~/.ssh/id_rsa.pub
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      
#      - name: ls
#        run: ls -Al  
        
#      - name: go to terraform config directory
#        run: cd yandex-cloud-terraform
        
#      - name: ls
#        run: ls -Al  
        
      - name: create vars file
        run: |
          cd yandex-cloud-terraform
          echo variable "oauth" { default = "${{ secrets.YC_OAUTH }}" } terraform.tf
          echo variable "cloud" { default = "${{ secrets.YC_CLOUD }}" } >> terraform.tf
          echo variable "folder" { default = "${{ secrets.YC_FOLDER }}" } >> terraform.tf
          
      - name: check format Terraform
        run: |
          cd yandex-cloud-terraform
          terraform fmt
        
      - name: init Terraform
        run: |
          cd yandex-cloud-terraform
          terraform init
        
      - name: validate Terraform
        run: |
          cd yandex-cloud-terraform
          terraform validate
        
      - name: plan Terraform
        run: |
          cd yandex-cloud-terraform
          terraform plan -var-file=terraform.tf
        
      - name: apply Terraform
        run: |
          cd yandex-cloud-terraform
          terraform apply -var-file=terraform.tf
        
#    - uses: hashicorp/terraform-github-actions/fmt@latest
#    - uses: hashicorp/terraform-github-actions/init@latest
#    - uses: hashicorp/terraform-github-actions/validate@latest
#    - uses: hashicorp/terraform-github-actions/plan@latest
#    - uses: hashicorp/terraform-github-actions/apply@latest
